apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-webserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: httpd-deploy 
  labels:
    app: webserver
spec:
  selector:
    matchLabels:
      app: webserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - image: httpd
        name: webserver
        ports:
        - containerPort: 80
          name: webserver
        volumeMounts:
        - name: webserver-pv
          mountPath: /usr/local/apache2/htdocs/
      volumes:
      - name: webserver-pv
        persistentVolumeClaim:
          claimName: pvc-webserver